### ISSUE TITLE
bitmap_set函数实现中有细节错误,导致内存分配异常

### ISSUE THREAD

**Issue by Huarkiou** [seaswalker/tiny-os#3]
https://github.com/seaswalker/tiny-os/blob/1c635f7069326ea7b058487486f3131a2717df8f/chapter8/memory_manager/lib/bitmap.c#L74-L78
  在bitmap.c中第78行`uint32_t bit_odd = byte_index % 8; `,
应改为`uint32_t bit_odd = `~~`byte_index`~~ `index % 8; `
否则会导致多次分配内存时，后面所有分配的虚拟地址映射到同一块物理地址

> 这个错误在chapter8一直到chapter10中都存在。

**Comment by seaswalker** [comment]
已修改～
